/**
 * ExecuteGetFunction - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: functions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetFunction Use Case
 *
 * DDD: Application use case for get Function.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetFunctionInput, GetFunctionOutput } from "../dto/function.dto";
import type { ExecutionContextService, IdGeneratorService } from "@ceilgas/services/_shared/index.js";
import type { FunctionRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetFunction {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly functionRepo: FunctionRepository
  ) {}

  async execute(input: GetFunctionInput): Promise<GetFunctionOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.fncId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).functionId) {
      throw new ValidationError("functionId is required");
    }
    const functionId = (input as any).functionId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.functionRepo.getFunction({ functionId: functionId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${functionId}`);
    }

    return entity as GetFunctionOutput;
  }
}
