/**
 * Dependency Container
 *
 * AUTO-GENERATED by codegen (api_server_domain_dependencies). Do not edit by hand.
 * Regenerate with: pnpm run codegen (domain list from platform/api-server/src/domains rescan).
 *
 * Manages dependency creation and caching per domain.
 */

import type { AdapterDynamoDBClient } from "@ceilgas/adapters";
import { getDynamoClientInstance } from "../lib/dependencies/domain-dependencies.js";
import { executionContextService } from "../lib/context/execution-context.service.js";
import {
  buildBoundsDomainModule,
  buildBuildsDomainModule,
  buildCertificatesDomainModule,
  buildFunctionsDomainModule,
  buildGriefingDomainModule,
  buildIdentityDomainModule,
  buildMonitorsDomainModule,
  buildPoliciesDomainModule,
  buildRecommendationsDomainModule,
} from "../domains/index.js";
import type {
  BoundsDomainModule,
  BuildsDomainModule,
  CertificatesDomainModule,
  FunctionsDomainModule,
  GriefingDomainModule,
  IdentityDomainModule,
  MonitorsDomainModule,
  PoliciesDomainModule,
  RecommendationsDomainModule,
} from "../domains/index.js";

class DependencyContainer {
  private readonly dynamoClient: AdapterDynamoDBClient;

  private boundsModule: BoundsDomainModule | null = null;
  private buildsModule: BuildsDomainModule | null = null;
  private certificatesModule: CertificatesDomainModule | null = null;
  private functionsModule: FunctionsDomainModule | null = null;
  private griefingModule: GriefingDomainModule | null = null;
  private identityModule: IdentityDomainModule | null = null;
  private monitorsModule: MonitorsDomainModule | null = null;
  private policiesModule: PoliciesDomainModule | null = null;
  private recommendationsModule: RecommendationsDomainModule | null = null;

  constructor(dynamoClient: AdapterDynamoDBClient) {
    this.dynamoClient = dynamoClient;
  }

  /**
   * Get bounds domain module
   */
  getBoundsDependencies(): BoundsDomainModule {
    if (!this.boundsModule) {
      this.boundsModule = buildBoundsDomainModule(this.dynamoClient);
    }
    return this.boundsModule;
  }

  /**
   * Get builds domain module
   */
  getBuildsDependencies(): BuildsDomainModule {
    if (!this.buildsModule) {
      this.buildsModule = buildBuildsDomainModule(this.dynamoClient);
    }
    return this.buildsModule;
  }

  /**
   * Get certificates domain module
   */
  getCertificatesDependencies(): CertificatesDomainModule {
    if (!this.certificatesModule) {
      this.certificatesModule = buildCertificatesDomainModule(this.dynamoClient);
    }
    return this.certificatesModule;
  }

  /**
   * Get functions domain module
   */
  getFunctionsDependencies(): FunctionsDomainModule {
    if (!this.functionsModule) {
      this.functionsModule = buildFunctionsDomainModule(this.dynamoClient);
    }
    return this.functionsModule;
  }

  /**
   * Get griefing domain module
   */
  getGriefingDependencies(): GriefingDomainModule {
    if (!this.griefingModule) {
      this.griefingModule = buildGriefingDomainModule(this.dynamoClient);
    }
    return this.griefingModule;
  }

  /**
   * Get identity domain module
   */
  getIdentityDependencies(): IdentityDomainModule {
    if (!this.identityModule) {
      this.identityModule = buildIdentityDomainModule(this.dynamoClient);
    }
    return this.identityModule;
  }

  /**
   * Get monitors domain module
   */
  getMonitorsDependencies(): MonitorsDomainModule {
    if (!this.monitorsModule) {
      this.monitorsModule = buildMonitorsDomainModule(this.dynamoClient);
    }
    return this.monitorsModule;
  }

  /**
   * Get policies domain module
   */
  getPoliciesDependencies(): PoliciesDomainModule {
    if (!this.policiesModule) {
      this.policiesModule = buildPoliciesDomainModule(this.dynamoClient);
    }
    return this.policiesModule;
  }

  /**
   * Get recommendations domain module
   */
  getRecommendationsDependencies(): RecommendationsDomainModule {
    if (!this.recommendationsModule) {
      this.recommendationsModule = buildRecommendationsDomainModule(this.dynamoClient);
    }
    return this.recommendationsModule;
  }

  clearBoundsDependencies(): void { this.boundsModule = null; }
  clearBuildsDependencies(): void { this.buildsModule = null; }
  clearCertificatesDependencies(): void { this.certificatesModule = null; }
  clearFunctionsDependencies(): void { this.functionsModule = null; }
  clearGriefingDependencies(): void { this.griefingModule = null; }
  clearIdentityDependencies(): void { this.identityModule = null; }
  clearMonitorsDependencies(): void { this.monitorsModule = null; }
  clearPoliciesDependencies(): void { this.policiesModule = null; }
  clearRecommendationsDependencies(): void { this.recommendationsModule = null; }

  getBoundsDependenciesForRequest(): BoundsDomainModule {
    return this.getBoundsDependencies();
  }

  getBuildsDependenciesForRequest(): BuildsDomainModule {
    return this.getBuildsDependencies();
  }

  getCertificatesDependenciesForRequest(): CertificatesDomainModule {
    return this.getCertificatesDependencies();
  }

  getFunctionsDependenciesForRequest(): FunctionsDomainModule {
    return this.getFunctionsDependencies();
  }

  getGriefingDependenciesForRequest(): GriefingDomainModule {
    return this.getGriefingDependencies();
  }

  getIdentityDependenciesForRequest(): IdentityDomainModule {
    return this.getIdentityDependencies();
  }

  getMonitorsDependenciesForRequest(): MonitorsDomainModule {
    return this.getMonitorsDependencies();
  }

  getPoliciesDependenciesForRequest(): PoliciesDomainModule {
    return this.getPoliciesDependencies();
  }

  getRecommendationsDependenciesForRequest(): RecommendationsDomainModule {
    return this.getRecommendationsDependencies();
  }

  /**
   * Clear all caches
   */
  clearAllCaches(): void {
    this.boundsModule = null;
    this.buildsModule = null;
    this.certificatesModule = null;
    this.functionsModule = null;
    this.griefingModule = null;
    this.identityModule = null;
    this.monitorsModule = null;
    this.policiesModule = null;
    this.recommendationsModule = null;
  }
}

let dependencyContainerInstance: DependencyContainer | null = null;

export function getDependencyContainer(): DependencyContainer {
  if (!dependencyContainerInstance) {
    const dynamoClient = getDynamoClientInstance();
    dependencyContainerInstance = new DependencyContainer(dynamoClient);
  }
  return dependencyContainerInstance;
}
