/**
 * ExecuteListBuilds - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: builds
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListBuilds Use Case
 *
 * DDD: Application use case for list Build.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListBuildsInput, ListBuildsOutput } from "../dto/build.dto";
import type { ExecutionContextService, IdGeneratorService } from "@ceilgas/services/_shared/index.js";
import type { BuildRepository } from "../ports";

export class ExecuteListBuilds {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly build: BuildRepository
  ) {}

  async execute(input: ListBuildsInput): Promise<ListBuildsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.bldId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.build.listBuilds({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListBuildsOutput;
  }
}
