/**
 * ExecuteGetBuild - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: builds
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetBuild Use Case
 *
 * DDD: Application use case for get Build.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetBuildInput, GetBuildOutput } from "../dto/build.dto";
import type { ExecutionContextService, IdGeneratorService } from "@ceilgas/services/_shared/index.js";
import type { BuildRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetBuild {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly build: BuildRepository
  ) {}

  async execute(input: GetBuildInput): Promise<GetBuildOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.bldId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).buildId) {
      throw new ValidationError("buildId is required");
    }
    const buildId = (input as any).buildId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.build.getBuild({ buildId: buildId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${buildId}`);
    }

    return entity as GetBuildOutput;
  }
}
