/**
 * ExecuteSubmitBuild - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: builds
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteSubmitBuild Use Case
 *
 * DDD: Application use case for create Build.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { SubmitBuildInput, SubmitBuildOutput } from "../dto/build.dto";
import type { ExecutionContextService, IdGeneratorService } from "@ceilgas/services/_shared/index.js";
import type { BuildRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteSubmitBuild {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly build: BuildRepository
  ) {}

  async execute(input: SubmitBuildInput): Promise<SubmitBuildOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.bldId();

    // All field names extracted from OpenAPI spec: analyserVersion, bytecodeHex, gasScheduleVersion, soliditySource, sourceLanguage
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.bytecodeHex) {
      throw new ValidationError("bytecodeHex is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (builds domain)
    const entityId = this.idGenerator.bldId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.build.submitBuild({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as SubmitBuildOutput;
  }
}
