/**
 * Policies Zod Schemas - Runtime validation schemas
 *
 * Generated by Zod Schemas Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { makeApi, Zodios, type ZodiosOptions } from '@zodios/core';
import { z } from 'zod';

const upsertCiPolicy_Body = z
  .object({
    name: z.string(),
    mode: z.enum(['certification', 'optimisation_hints']),
    failClosedOnIncompleteness: z.boolean(),
    nonConstantSeverity: z.enum(['info', 'warn', 'fail']),
    exceptionNotes: z.array(z.string()).optional(),
  })
  .passthrough();

export const schemas: any = {
  upsertCiPolicy_Body,
};

const endpoints = makeApi([
  {
    method: 'get',
    path: '/v1/policies',
    alias: 'listCiPolicies',
    requestFormat: 'json',
    parameters: [
      {
        name: 'cursor',
        type: 'Query',
        schema: z.string().optional(),
      },
      {
        name: 'limit',
        type: 'Query',
        schema: z.number().int().gte(1).lte(100).optional().default(25),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            items: z.array(
              z
                .object({
                  id: z.string().regex(/^pol_[0-9A-HJKMNP-TV-Z]{26}$/),
                  name: z.string(),
                  mode: z.enum(['certification', 'optimisation_hints']),
                  failClosedOnIncompleteness: z.boolean(),
                  nonConstantSeverity: z.enum(['info', 'warn', 'fail']),
                  exceptionNotes: z.array(z.string()).optional(),
                  updatedAt: z.string().datetime({ offset: true }).optional(),
                })
                .passthrough()
            ),
            nextCursor: z.string().optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/policies',
    alias: 'upsertCiPolicy',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: upsertCiPolicy_Body,
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            id: z.string().regex(/^pol_[0-9A-HJKMNP-TV-Z]{26}$/),
            name: z.string(),
            mode: z.enum(['certification', 'optimisation_hints']),
            failClosedOnIncompleteness: z.boolean(),
            nonConstantSeverity: z.enum(['info', 'warn', 'fail']),
            exceptionNotes: z.array(z.string()).optional(),
            updatedAt: z.string().datetime({ offset: true }).optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 400,
        description: `Malformed request`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'get',
    path: '/v1/policies/:policyId',
    alias: 'getCiPolicy',
    requestFormat: 'json',
    parameters: [
      {
        name: 'policyId',
        type: 'Path',
        schema: z.string().regex(/^pol_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            id: z.string().regex(/^pol_[0-9A-HJKMNP-TV-Z]{26}$/),
            name: z.string(),
            mode: z.enum(['certification', 'optimisation_hints']),
            failClosedOnIncompleteness: z.boolean(),
            nonConstantSeverity: z.enum(['info', 'warn', 'fail']),
            exceptionNotes: z.array(z.string()).optional(),
            updatedAt: z.string().datetime({ offset: true }).optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/policies/:policyId/evaluate',
    alias: 'evaluateCiPolicy',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: z
          .object({ buildId: z.string().regex(/^bld_[0-9A-HJKMNP-TV-Z]{26}$/) })
          .passthrough(),
      },
      {
        name: 'policyId',
        type: 'Path',
        schema: z.string().regex(/^pol_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            buildId: z.string().regex(/^bld_[0-9A-HJKMNP-TV-Z]{26}$/),
            policyId: z
              .string()
              .regex(/^pol_[0-9A-HJKMNP-TV-Z]{26}$/)
              .optional(),
            passed: z.boolean(),
            mode: z.enum(['certification', 'optimisation_hints']),
            violations: z
              .array(
                z
                  .object({
                    code: z.enum([
                      'non_constant_gas',
                      'incompleteness',
                      'cfg_incomplete',
                    ]),
                    message: z.string(),
                    functionId: z
                      .string()
                      .regex(/^fnc_[0-9A-HJKMNP-TV-Z]{26}$/)
                      .optional(),
                  })
                  .passthrough()
              )
              .optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
]);

export const api: any = new Zodios('https://api.ceilgas.local', endpoints);

export function createApiClient(baseUrl: string, options?: ZodiosOptions): any {
  return new Zodios(baseUrl, endpoints, options);
}
