/**
 * BoundRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: bounds
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * BoundRepository Port
 *
 * DDD: Application port for boundrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetFunctionBoundsInput, GetFunctionBoundsOutput, ListBoundsInput, ListBoundsOutput } from "../dto/bound.dto";
export interface BoundRepository {
  getFunctionBounds(input: GetFunctionBoundsInput): Promise<GetFunctionBoundsOutput>;
  listBounds(input: ListBoundsInput): Promise<ListBoundsOutput>;
}

export type { GetFunctionBoundsInput, GetFunctionBoundsOutput, ListBoundsInput, ListBoundsOutput } from "../dto/bound.dto";
