/**
 * Routes for Certificate
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: certificates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getGasCertificate, issueGasCertificate, listGasCertificates } from "../handlers/certificate.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function certificateRoutes(fastify: FastifyInstance) {
  // POST /v1/certificates (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/certificates",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getCertificatesDependenciesForRequest();
        await issueGasCertificate(request, reply, deps);
      });
    }
  );


  // GET /v1/certificates (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/certificates",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getCertificatesDependenciesForRequest();
        await listGasCertificates(request, reply, deps);
      });
    }
  );


  // GET /v1/certificates/{certificateId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/certificates/:certificateId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { certificateId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getCertificatesDependenciesForRequest();
        await getGasCertificate(request, reply, deps);
      });
    }
  );


}
