/**
 * Builds DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: builds
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Builds Domain Module - Composition root
 *
 * DDD: Composition root for builds domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  BuildRepositoryAdapter,
} from "@ceilgas/adapters/builds";
import { getIdGeneratorService } from "@ceilgas/adapters";
import type { AdapterDynamoDBClient } from "@ceilgas/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteGetBuild,
  ExecuteListBuilds,
  ExecuteSubmitBuild,
} from "@ceilgas/services/builds/usecases";
// Ports (interfaces)
import type {
  BuildRepository,
} from "@ceilgas/services/builds/ports";

export interface BuildsDomainModule {
  repos: {
    builds: BuildRepository;
  };
  useCases: {
    builds: {
      create: ExecuteSubmitBuild;
      get: ExecuteGetBuild;
      list: ExecuteListBuilds;
    };
  };
}

export function buildBuildsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): BuildsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      builds?: BuildRepository;
    } = {};

    obj.builds = new BuildRepositoryAdapter(dynamoClient);
    return {
      builds: obj.builds!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    builds: {
      create: new ExecuteSubmitBuild(executionContext, idGenerator, repos.builds),
      get: new ExecuteGetBuild(executionContext, idGenerator, repos.builds),
      list: new ExecuteListBuilds(executionContext, idGenerator, repos.builds),
    },
  };
  return { repos, useCases: useCases as BuildsDomainModule["useCases"] };
}
