/**
 * Certificates DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: certificates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Certificates Domain Module - Composition root
 *
 * DDD: Composition root for certificates domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  CertificateRepositoryAdapter,
} from "@ceilgas/adapters/certificates";
import { getIdGeneratorService } from "@ceilgas/adapters";
import type { AdapterDynamoDBClient } from "@ceilgas/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteGetGasCertificate,
  ExecuteIssueGasCertificate,
  ExecuteListGasCertificates,
} from "@ceilgas/services/certificates/usecases";
// Ports (interfaces)
import type {
  CertificateRepository,
} from "@ceilgas/services/certificates/ports";

export interface CertificatesDomainModule {
  repos: {
    certificates: CertificateRepository;
  };
  useCases: {
    certificates: {
      get: ExecuteGetGasCertificate;
      list: ExecuteListGasCertificates;
    };
  };
}

export function buildCertificatesDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): CertificatesDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      certificates?: CertificateRepository;
    } = {};

    obj.certificates = new CertificateRepositoryAdapter(dynamoClient);
    return {
      certificates: obj.certificates!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    certificates: {
      get: new ExecuteGetGasCertificate(executionContext, idGenerator, repos.certificates),
      list: new ExecuteListGasCertificates(executionContext, idGenerator, repos.certificates),
    },
  };
  return { repos, useCases: useCases as CertificatesDomainModule["useCases"] };
}
