/**
 * Routes for Build
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: builds
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getBuild, listBuilds, submitBuild } from "../handlers/build.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function buildRoutes(fastify: FastifyInstance) {
  // GET /v1/builds (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/builds",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getBuildsDependenciesForRequest();
        await listBuilds(request, reply, deps);
      });
    }
  );


  // POST /v1/builds (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/builds",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getBuildsDependenciesForRequest();
        await submitBuild(request, reply, deps);
      });
    }
  );


  // GET /v1/builds/{buildId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/builds/:buildId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { buildId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getBuildsDependenciesForRequest();
        await getBuild(request, reply, deps);
      });
    }
  );


}
