/**
 * Policies DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Policies Domain Module - Composition root
 *
 * DDD: Composition root for policies domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  EvaluateRepositoryAdapter,
  PolicyRepositoryAdapter,
} from "@ceilgas/adapters/policies";
import { getIdGeneratorService } from "@ceilgas/adapters";
import type { AdapterDynamoDBClient } from "@ceilgas/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteEvaluateCiPolicy,
  ExecuteGetCiPolicy,
  ExecuteListCiPolicies,
  ExecuteUpsertCiPolicy,
} from "@ceilgas/services/policies/usecases";
// Ports (interfaces)
import type {
  EvaluateRepository,
  PolicyRepository,
} from "@ceilgas/services/policies/ports";

export interface PoliciesDomainModule {
  repos: {
    evaluates: EvaluateRepository;
    policies: PolicyRepository;
  };
  useCases: {
    evaluates: {
      create: ExecuteEvaluateCiPolicy;
    };
    policies: {
      get: ExecuteGetCiPolicy;
      list: ExecuteListCiPolicies;
    };
  };
}

export function buildPoliciesDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): PoliciesDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      evaluates?: EvaluateRepository;
      policies?: PolicyRepository;
    } = {};

    obj.evaluates = new EvaluateRepositoryAdapter(dynamoClient);
    obj.policies = new PolicyRepositoryAdapter(dynamoClient);
    return {
      evaluates: obj.evaluates!,
      policies: obj.policies!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    evaluates: {
      create: new ExecuteEvaluateCiPolicy(executionContext, idGenerator, repos.evaluates),
    },
    policies: {
      get: new ExecuteGetCiPolicy(executionContext, idGenerator, repos.policies),
      list: new ExecuteListCiPolicies(executionContext, idGenerator, repos.policies),
    },
  };
  return { repos, useCases: useCases as PoliciesDomainModule["useCases"] };
}
