/**
 * Routes for Evaluate
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { evaluateCiPolicy } from "../handlers/evaluate.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function evaluateRoutes(fastify: FastifyInstance) {
  // POST /v1/policies/{policyId}/evaluate (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/policies/:policyId/evaluate",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { policyId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getPoliciesDependenciesForRequest();
        await evaluateCiPolicy(request, reply, deps);
      });
    }
  );


}
