/**
 * Routes for Policy
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getCiPolicy, listCiPolicies, upsertCiPolicy } from "../handlers/policy.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function policyRoutes(fastify: FastifyInstance) {
  // GET /v1/policies (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/policies",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getPoliciesDependenciesForRequest();
        await listCiPolicies(request, reply, deps);
      });
    }
  );


  // POST /v1/policies (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/policies",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getPoliciesDependenciesForRequest();
        await upsertCiPolicy(request, reply, deps);
      });
    }
  );


  // GET /v1/policies/{policyId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/policies/:policyId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { policyId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getPoliciesDependenciesForRequest();
        await getCiPolicy(request, reply, deps);
      });
    }
  );


}
