/**
 * GetGasCertificate handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: certificates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getGasCertificate } from "@ceilgas/api-server/domains/certificates/handlers";
import type { CertificatesDDDDependencies } from "@ceilgas/api-server/domains/certificates";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@ceilgas/tests/shared";
import { CERTIFICATES_USE_CASES } from "../__factories__/use-cases.js";

describe("GetGasCertificate", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: CertificatesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<CertificatesDDDDependencies>(
      CERTIFICATES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetGasCertificate, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { certificateId: entity.id };

    await getGasCertificate(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetGasCertificate.execute).toHaveBeenCalledWith(expect.objectContaining({ certificateId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { certificateId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetGasCertificate, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getGasCertificate(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
