/**
 * Build DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: builds
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Build DTOs
 *
 * DDD: Application DTOs for Build use cases.
 */

import type { GetBuildParams, ListBuildsParams, SubmitBuildRequestInput } from "@ceilgas/core/builds/types";

export type ListBuildsInput = ListBuildsParams;

export type SubmitBuildInput = SubmitBuildRequestInput;

export type GetBuildInput = GetBuildParams;

export type ListBuildsOutput = {};

export type SubmitBuildOutput = {};

export type GetBuildOutput = {};
