/**
 * CreateGriefingEstimate handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: griefing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { createGriefingEstimate } from "@ceilgas/api-server/domains/griefing/handlers";
import type { GriefingDDDDependencies } from "@ceilgas/api-server/domains/griefing";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@ceilgas/tests/shared";
import { GRIEFING_USE_CASES } from "../__factories__/use-cases.js";

describe("CreateGriefingEstimate", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: GriefingDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<GriefingDDDDependencies>(
      GRIEFING_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeCreateGriefingEstimate, "execute").mockResolvedValue(useCaseResult);

    await createGriefingEstimate(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeCreateGriefingEstimate.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
