/**
 * GetBound DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: bounds
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetFunctionBoundsParams } from "@ceilgas/core/bounds";

export function createGetBoundRequest(overrides: Partial<GetFunctionBoundsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
