/**
 * Alert DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monitors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Alert DTOs
 *
 * DDD: Application DTOs for Alert use cases.
 */

import type { ListMonitorAlertsParams } from "@ceilgas/core/monitors/types";

export type ListMonitorAlertsInput = ListMonitorAlertsParams;

export type ListMonitorAlertsOutput = {};
