/**
 * Domain routes – register all domain route modules.
 *
 * AUTO-GENERATED by codegen (api_server_domain_routes). Do not edit by hand.
 * Rescans platform/api-server/src/domains and includes only domains that have
 * routes/index.ts and dependencies/{domain}-ddd.dependencies.ts.
 * Extension excludes/imports from x-codegen.api-server.extensions in OpenAPI YAML.
 */

import type { FastifyInstance } from "fastify";
import { registerDomainFromModule } from "./route-registration.js";

// Static imports so the bundle includes all domain route modules
import * as boundsRoutes from "../../domains/bounds/routes/index.js";
import * as buildsRoutes from "../../domains/builds/routes/index.js";
import * as certificatesRoutes from "../../domains/certificates/routes/index.js";
import * as functionsRoutes from "../../domains/functions/routes/index.js";
import * as griefingRoutes from "../../domains/griefing/routes/index.js";
import * as identityRoutes from "../../domains/identity/routes/index.js";
import * as monitorsRoutes from "../../domains/monitors/routes/index.js";
import * as policiesRoutes from "../../domains/policies/routes/index.js";
import * as recommendationsRoutes from "../../domains/recommendations/routes/index.js";

const DOMAIN_MODULES: Array<{
  domain: string;
  mod: Record<string, unknown>;
  exclude?: string[];
}> = [
  { domain: "bounds", mod: boundsRoutes },
  { domain: "builds", mod: buildsRoutes },
  { domain: "certificates", mod: certificatesRoutes },
  { domain: "functions", mod: functionsRoutes },
  { domain: "griefing", mod: griefingRoutes },
  {
    domain: "identity", mod: identityRoutes,
    exclude: ["authRoutes", "loginRoutes", "logoutRoutes", "signupRoutes", "sessionRoutes", "refreshRoutes", "tokenRoutes", "profileRoutes"],
  },
  { domain: "monitors", mod: monitorsRoutes },
  { domain: "policies", mod: policiesRoutes },
  { domain: "recommendations", mod: recommendationsRoutes },
];

export async function registerAllDomainRoutes(
  fastify: FastifyInstance,
): Promise<void> {
  console.log("[DEBUG] Registering domain routes...");
  try {
    for (const { domain, mod, exclude } of DOMAIN_MODULES) {
      await registerDomainFromModule(fastify, domain, mod, exclude ?? []);
    }
    console.log("[DEBUG] ✅ All domain routes registered");
  } catch (error: unknown) {
    const err = error instanceof Error ? error : new Error(String(error));
    console.error("[DEBUG] ❌ Error registering domain routes:", err.message);
    if (err.stack) console.error(err.stack);
    throw error;
  }
}
