/**
 * System Routes - Health check and routes listing
 *
 * AUTO-GENERATED by codegen (api_server_system_routes). Do not edit by hand.
 * Domains and routeExamples are derived from discovered api-server domains and
 * each domain's OpenAPI bundled spec.
 */

import type { FastifyInstance } from "fastify";
import {
  getCoreTableName,
  getBaseTableName,
  getAnalyticsTableName,
} from "@ceilgas/adapters";
import { getRegisteredRoutes } from "./route-registry.js";

/**
 * Register system routes (health check, routes listing)
 */
export function registerSystemRoutes(fastify: FastifyInstance): void {
  // Health check (public - no auth required)
  fastify.get("/health", { config: { scope: "public" } }, async () => {
    try {
      const coreTable = getCoreTableName();
      const baseTable = getBaseTableName();
      const analyticsTable = getAnalyticsTableName();
      return {
        status: "ok",
        database: "dynamodb",
        tables: {
          core: coreTable,
          base: baseTable,
          analytics: analyticsTable,
        },
      };
    } catch (error: unknown) {
      const errorMessage =
        error instanceof Error ? error.message : String(error);
      fastify.log.warn({ error: errorMessage }, "Health check failed");
      return { status: "error", database: "disconnected", error: errorMessage };
    }
  });

  // Routes listing endpoint (public)
  fastify.get("/routes", { config: { scope: "public" } }, async () => {
    const domains = [
      "bounds", "builds", "certificates", "functions", "griefing", "identity", "monitors", "policies", "recommendations"
    ];

    const routeExamples: Record<
      string,
      Array<{ method: string; path: string; description?: string }>
    > = {
      bounds: [{ method: "GET", path: "/v1/functions/:functionId/bounds" }, { method: "GET", path: "/v1/bounds" }],
      builds: [{ method: "GET", path: "/v1/builds" }, { method: "POST", path: "/v1/builds" }, { method: "GET", path: "/v1/builds/:buildId" }],
      certificates: [{ method: "GET", path: "/v1/certificates" }, { method: "POST", path: "/v1/certificates" }, { method: "GET", path: "/v1/certificates/:certificateId" }],
      functions: [{ method: "GET", path: "/v1/builds/:buildId/functions" }, { method: "GET", path: "/v1/functions/:functionId" }],
      griefing: [{ method: "GET", path: "/v1/griefing/estimates" }, { method: "POST", path: "/v1/griefing/estimates" }],
      identity: [],
      monitors: [{ method: "GET", path: "/v1/monitors" }, { method: "POST", path: "/v1/monitors" }, { method: "GET", path: "/v1/monitors/:monitorId/alerts" }],
      policies: [{ method: "GET", path: "/v1/policies" }, { method: "POST", path: "/v1/policies" }, { method: "GET", path: "/v1/policies/:policyId" }, { method: "POST", path: "/v1/policies/:policyId/evaluate" }],
      recommendations: [{ method: "GET", path: "/v1/recommendations" }, { method: "POST", path: "/v1/recommendations" }],
    };

    return {
      baseUrl: "http://localhost:4000",
      routePattern: "/orgs/:orgId/{domain}/{resource}",
      authentication:
        "All routes (except /health and /routes) require JWT token in Authorization header",
      domains: domains.sort(),
      routeExamples,
      systemRoutes: [
        { method: "GET", path: "/health", description: "Health check endpoint" },
        { method: "GET", path: "/routes", description: "List available routes" },
      ],
      note: "Replace :orgId with actual organization ID. All domain routes require authentication.",
    };
  });

  // Full route list for API tester page (public)
  fastify.get("/routes/full", { config: { scope: "public" } }, async () => {
    const routes = getRegisteredRoutes();
    const byDomain: Record<
      string,
      Array<{ method: string; path: string }>
    > = {};
    const system: Array<{ method: string; path: string }> = [];
    for (const r of routes) {
      const m = r.path.match(/^\/orgs\/:orgId\/([^/]+)/);
      if (m) {
        const domain = m[1];
        if (!byDomain[domain]) byDomain[domain] = [];
        byDomain[domain].push(r);
      } else {
        system.push(r);
      }
    }
    return {
      baseUrl: "http://localhost:4000",
      total: routes.length,
      system,
      byDomain: Object.keys(byDomain)
        .sort()
        .reduce(
          (acc, k) => ({ ...acc, [k]: byDomain[k] }),
          {} as Record<string, Array<{ method: string; path: string }>>,
        ),
    };
  });
}
