/**
 * Handlers for Alert
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monitors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { MonitorsDomainModule } from "../dependencies/monitors-ddd.dependencies.js";
import type { ListMonitorAlertsInput } from "@ceilgas/services/monitors";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/monitors/{monitorId}/alerts
 * Operation: listMonitorAlerts
 */
export async function listMonitorAlerts(
  request: FastifyRequest<{ Params: { monitorId: string }; Querystring: { cursor?: string | string[], limit?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: MonitorsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListMonitorAlertsInput = {
    monitorId: request.params.monitorId,
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.alerts.list.execute(input);
  return reply.code(200).send(result);
}


