/**
 * FunctionRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: functions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * FunctionRepository Port
 *
 * DDD: Application port for functionrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetFunctionInput, GetFunctionOutput, ListFunctionsInput, ListFunctionsOutput } from "../dto/function.dto";
export interface FunctionRepository {
  listFunctions(input: ListFunctionsInput): Promise<ListFunctionsOutput>;
  getFunction(input: GetFunctionInput): Promise<GetFunctionOutput>;
}

export type { GetFunctionInput, GetFunctionOutput, ListFunctionsInput, ListFunctionsOutput } from "../dto/function.dto";
