/**
 * Routes for Function
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: functions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getFunction, listFunctions } from "../handlers/function.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function functionRoutes(fastify: FastifyInstance) {
  // GET /v1/builds/{buildId}/functions (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/builds/:buildId/functions",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { buildId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getFunctionsDependenciesForRequest();
        await listFunctions(request, reply, deps);
      });
    }
  );


  // GET /v1/functions/{functionId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/functions/:functionId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { functionId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getFunctionsDependenciesForRequest();
        await getFunction(request, reply, deps);
      });
    }
  );


}
