/**
 * EstimateRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: griefing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * EstimateRepository Port
 *
 * DDD: Application port for estimaterepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateGriefingEstimateInput, CreateGriefingEstimateOutput, ListGriefingEstimatesInput, ListGriefingEstimatesOutput } from "../dto/estimate.dto";
export interface EstimateRepository {
  listGriefingEstimates(input: ListGriefingEstimatesInput): Promise<ListGriefingEstimatesOutput>;
  createGriefingEstimate(input: CreateGriefingEstimateInput): Promise<CreateGriefingEstimateOutput>;
}

export type { CreateGriefingEstimateInput, CreateGriefingEstimateOutput, ListGriefingEstimatesInput, ListGriefingEstimatesOutput } from "../dto/estimate.dto";
