/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: builds
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Builds Domain Use Cases
 * 
 * List of all use case names for the builds domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const BUILDS_USE_CASES = [
  "executeGetBuild",
  "executeListBuilds",
  "executeSubmitBuild"
] as const;
