/**
 * Evaluate DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Evaluate DTOs
 *
 * DDD: Application DTOs for Evaluate use cases.
 */

import type { EvaluateCiPolicyParams, EvaluateCiPolicyRequestInput } from "@ceilgas/core/policies/types";

export type EvaluateCiPolicyInput = EvaluateCiPolicyParams & EvaluateCiPolicyRequestInput;

export type EvaluateCiPolicyOutput = {};
