/**
 * Policy DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Policy DTOs
 *
 * DDD: Application DTOs for Policy use cases.
 */

import type { GetCiPolicyParams, ListCiPoliciesParams, UpsertCiPolicyRequestInput } from "@ceilgas/core/policies/types";

export type ListCiPoliciesInput = ListCiPoliciesParams;

export type UpsertCiPolicyInput = UpsertCiPolicyRequestInput;

export type GetCiPolicyInput = GetCiPolicyParams;

export type ListCiPoliciesOutput = {};

export type UpsertCiPolicyOutput = {};

export type GetCiPolicyOutput = {};
