/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List CI policies */
        get: operations["listCiPolicies"];
        put?: never;
        /** Create or update a CI policy */
        post: operations["upsertCiPolicy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/policies/{policyId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                policyId: string;
            };
            cookie?: never;
        };
        /** Get a CI policy */
        get: operations["getCiPolicy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/policies/{policyId}/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                policyId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Evaluate CI policy against a build */
        post: operations["evaluateCiPolicy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description RFC 7807 Problem Details (provisional mapping for gateway errors). */
        Problem: {
            /**
             * Format: uri
             * @description URI reference identifying the problem type.
             */
            type?: string;
            /** @description Short human-readable summary. */
            title?: string;
            /** @description HTTP status code. */
            status?: number;
            /** @description Human-readable explanation specific to this occurrence. */
            detail?: string;
            /**
             * Format: uri
             * @description URI reference identifying this occurrence.
             */
            instance?: string;
            /** @description Optional machine-readable error code from the gateway. */
            code?: string;
        } & {
            [key: string]: unknown;
        };
        /** @description CI policy id (`pol_…`). */
        PolicyId: string;
        /**
         * @description Certification must not be conflated with optimisation (BR-10).
         * @enum {string}
         */
        PolicyMode: "certification" | "optimisation_hints";
        /** @enum {string} */
        NonConstantSeverity: "info" | "warn" | "fail";
        CiPolicy: {
            /** @description CI policy id (`pol_…`). */
            id: string;
            name: string;
            /**
             * @description Certification must not be conflated with optimisation (BR-10).
             * @enum {string}
             */
            mode: "certification" | "optimisation_hints";
            /** @description Refuse certification / fail CI when incompleteness present (BR-3). */
            failClosedOnIncompleteness: boolean;
            /** @enum {string} */
            nonConstantSeverity: "info" | "warn" | "fail";
            /** @description Dual-note approved exceptions for non-constant gas. */
            exceptionNotes?: string[];
            /** Format: date-time */
            updatedAt?: string;
        };
        CiPolicyListData: {
            items: {
                /** @description CI policy id (`pol_…`). */
                id: string;
                name: string;
                /**
                 * @description Certification must not be conflated with optimisation (BR-10).
                 * @enum {string}
                 */
                mode: "certification" | "optimisation_hints";
                /** @description Refuse certification / fail CI when incompleteness present (BR-3). */
                failClosedOnIncompleteness: boolean;
                /** @enum {string} */
                nonConstantSeverity: "info" | "warn" | "fail";
                /** @description Dual-note approved exceptions for non-constant gas. */
                exceptionNotes?: string[];
                /** Format: date-time */
                updatedAt?: string;
            }[];
            nextCursor?: string;
        };
        ResponseMeta: {
            /**
             * Format: uuid
             * @description Correlation id for this HTTP request.
             */
            requestId?: string;
            /** @description Optional end-to-end correlation id. */
            correlationId?: string;
            /**
             * Format: date-time
             * @description Server time when the payload was produced.
             */
            generatedAt?: string;
        };
        CiPolicyListResponse: {
            data: {
                items: {
                    /** @description CI policy id (`pol_…`). */
                    id: string;
                    name: string;
                    /**
                     * @description Certification must not be conflated with optimisation (BR-10).
                     * @enum {string}
                     */
                    mode: "certification" | "optimisation_hints";
                    /** @description Refuse certification / fail CI when incompleteness present (BR-3). */
                    failClosedOnIncompleteness: boolean;
                    /** @enum {string} */
                    nonConstantSeverity: "info" | "warn" | "fail";
                    /** @description Dual-note approved exceptions for non-constant gas. */
                    exceptionNotes?: string[];
                    /** Format: date-time */
                    updatedAt?: string;
                }[];
                nextCursor?: string;
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
        CiPolicyUpsert: {
            name: string;
            /**
             * @description Certification must not be conflated with optimisation (BR-10).
             * @enum {string}
             */
            mode: "certification" | "optimisation_hints";
            failClosedOnIncompleteness: boolean;
            /** @enum {string} */
            nonConstantSeverity: "info" | "warn" | "fail";
            exceptionNotes?: string[];
        };
        CiPolicyResponse: {
            data: {
                /** @description CI policy id (`pol_…`). */
                id: string;
                name: string;
                /**
                 * @description Certification must not be conflated with optimisation (BR-10).
                 * @enum {string}
                 */
                mode: "certification" | "optimisation_hints";
                /** @description Refuse certification / fail CI when incompleteness present (BR-3). */
                failClosedOnIncompleteness: boolean;
                /** @enum {string} */
                nonConstantSeverity: "info" | "warn" | "fail";
                /** @description Dual-note approved exceptions for non-constant gas. */
                exceptionNotes?: string[];
                /** Format: date-time */
                updatedAt?: string;
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
        /** @description Contract build id (`bld_…`). */
        BuildId: string;
        /** @description Public function id (`fnc_…`). */
        FunctionId: string;
        CiPolicyGateResult: {
            /** @description Contract build id (`bld_…`). */
            buildId: string;
            /** @description CI policy id (`pol_…`). */
            policyId?: string;
            passed: boolean;
            /**
             * @description Certification must not be conflated with optimisation (BR-10).
             * @enum {string}
             */
            mode: "certification" | "optimisation_hints";
            violations?: {
                /** @enum {string} */
                code: "non_constant_gas" | "incompleteness" | "cfg_incomplete";
                message: string;
                /** @description Public function id (`fnc_…`). */
                functionId?: string;
            }[];
        };
        CiPolicyGateResultResponse: {
            data: {
                /** @description Contract build id (`bld_…`). */
                buildId: string;
                /** @description CI policy id (`pol_…`). */
                policyId?: string;
                passed: boolean;
                /**
                 * @description Certification must not be conflated with optimisation (BR-10).
                 * @enum {string}
                 */
                mode: "certification" | "optimisation_hints";
                violations?: {
                    /** @enum {string} */
                    code: "non_constant_gas" | "incompleteness" | "cfg_incomplete";
                    message: string;
                    /** @description Public function id (`fnc_…`). */
                    functionId?: string;
                }[];
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
    };
    responses: {
        /** @description Error (RFC 7807 Problem Details) */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        /** @description Missing or invalid API key */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        /** @description Malformed request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
    };
    parameters: {
        /** @description Opaque keyset pagination cursor. */
        Cursor: string;
        /** @description Page size (1–100). */
        Limit: number;
        /**
         * @description Client-supplied key for safe retries on mutating POSTs (≤128 chars).
         *     Replay with the same key and body returns the original result; different
         *     body with the same key yields 409.
         */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listCiPolicies: {
        parameters: {
            query?: {
                /** @description Opaque keyset pagination cursor. */
                cursor?: string;
                /** @description Page size (1–100). */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Policies page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: {
                                /** @description CI policy id (`pol_…`). */
                                id: string;
                                name: string;
                                /**
                                 * @description Certification must not be conflated with optimisation (BR-10).
                                 * @enum {string}
                                 */
                                mode: "certification" | "optimisation_hints";
                                /** @description Refuse certification / fail CI when incompleteness present (BR-3). */
                                failClosedOnIncompleteness: boolean;
                                /** @enum {string} */
                                nonConstantSeverity: "info" | "warn" | "fail";
                                /** @description Dual-note approved exceptions for non-constant gas. */
                                exceptionNotes?: string[];
                                /** Format: date-time */
                                updatedAt?: string;
                            }[];
                            nextCursor?: string;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    upsertCiPolicy: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Client-supplied key for safe retries on mutating POSTs (≤128 chars).
                 *     Replay with the same key and body returns the original result; different
                 *     body with the same key yields 409.
                 */
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    /**
                     * @description Certification must not be conflated with optimisation (BR-10).
                     * @enum {string}
                     */
                    mode: "certification" | "optimisation_hints";
                    failClosedOnIncompleteness: boolean;
                    /** @enum {string} */
                    nonConstantSeverity: "info" | "warn" | "fail";
                    exceptionNotes?: string[];
                };
            };
        };
        responses: {
            /** @description Policy saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            /** @description CI policy id (`pol_…`). */
                            id: string;
                            name: string;
                            /**
                             * @description Certification must not be conflated with optimisation (BR-10).
                             * @enum {string}
                             */
                            mode: "certification" | "optimisation_hints";
                            /** @description Refuse certification / fail CI when incompleteness present (BR-3). */
                            failClosedOnIncompleteness: boolean;
                            /** @enum {string} */
                            nonConstantSeverity: "info" | "warn" | "fail";
                            /** @description Dual-note approved exceptions for non-constant gas. */
                            exceptionNotes?: string[];
                            /** Format: date-time */
                            updatedAt?: string;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Malformed request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    getCiPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                policyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Policy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            /** @description CI policy id (`pol_…`). */
                            id: string;
                            name: string;
                            /**
                             * @description Certification must not be conflated with optimisation (BR-10).
                             * @enum {string}
                             */
                            mode: "certification" | "optimisation_hints";
                            /** @description Refuse certification / fail CI when incompleteness present (BR-3). */
                            failClosedOnIncompleteness: boolean;
                            /** @enum {string} */
                            nonConstantSeverity: "info" | "warn" | "fail";
                            /** @description Dual-note approved exceptions for non-constant gas. */
                            exceptionNotes?: string[];
                            /** Format: date-time */
                            updatedAt?: string;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    evaluateCiPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                policyId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Contract build id (`bld_…`). */
                    buildId: string;
                };
            };
        };
        responses: {
            /** @description Gate result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            /** @description Contract build id (`bld_…`). */
                            buildId: string;
                            /** @description CI policy id (`pol_…`). */
                            policyId?: string;
                            passed: boolean;
                            /**
                             * @description Certification must not be conflated with optimisation (BR-10).
                             * @enum {string}
                             */
                            mode: "certification" | "optimisation_hints";
                            violations?: {
                                /** @enum {string} */
                                code: "non_constant_gas" | "incompleteness" | "cfg_incomplete";
                                message: string;
                                /** @description Public function id (`fnc_…`). */
                                functionId?: string;
                            }[];
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
