/**
 * Routes for Estimate
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: griefing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createGriefingEstimate, listGriefingEstimates } from "../handlers/estimate.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function estimateRoutes(fastify: FastifyInstance) {
  // POST /v1/griefing/estimates (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/griefing/estimates",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getGriefingDependenciesForRequest();
        await createGriefingEstimate(request, reply, deps);
      });
    }
  );


  // GET /v1/griefing/estimates (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/griefing/estimates",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getGriefingDependenciesForRequest();
        await listGriefingEstimates(request, reply, deps);
      });
    }
  );


}
