/**
 * ExecuteCreateGriefingEstimate - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: griefing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateGriefingEstimate Use Case
 *
 * DDD: Application use case for create Estimate.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateGriefingEstimateInput, CreateGriefingEstimateOutput } from "../dto/estimate.dto";
import type { ExecutionContextService, IdGeneratorService } from "@ceilgas/services/_shared/index.js";
import type { EstimateRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateGriefingEstimate {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly estimate: EstimateRepository
  ) {}

  async execute(input: CreateGriefingEstimateInput): Promise<CreateGriefingEstimateOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.grfId();

    // All field names extracted from OpenAPI spec: assumptions, functionId, notes
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.functionId) {
      throw new ValidationError("functionId is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (griefing domain)
    const entityId = this.idGenerator.grfId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.estimate.createGriefingEstimate({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateGriefingEstimateOutput;
  }
}
