/**
 * ExecuteListGriefingEstimates - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: griefing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListGriefingEstimates Use Case
 *
 * DDD: Application use case for list Estimate.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListGriefingEstimatesInput, ListGriefingEstimatesOutput } from "../dto/estimate.dto";
import type { ExecutionContextService, IdGeneratorService } from "@ceilgas/services/_shared/index.js";
import type { EstimateRepository } from "../ports";

export class ExecuteListGriefingEstimates {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly estimate: EstimateRepository
  ) {}

  async execute(input: ListGriefingEstimatesInput): Promise<ListGriefingEstimatesOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.grfId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.estimate.listGriefingEstimates({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListGriefingEstimatesOutput;
  }
}
