/**
 * GetCertificate DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: certificates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetGasCertificateParams } from "@ceilgas/core/certificates";

export function createGetCertificateRequest(overrides: Partial<GetGasCertificateParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
