/**
 * Main Core Package Index
 *
 * Generated by Main Index Builder Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: griefing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * @ceilgas/core - Main Barrel Export
 *
 * Central export point for all core business logic, entities, repositories, and types
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended for new code)
 *   import { activity, ai } from "@ceilgas/core";
 *   const { repositories, types } = activity;
 *
 *   // Direct domain imports (via package.json exports)
 *   import { ActivityRepository } from "@ceilgas/core/activity/repositories/index.js";
 *   import { ActivityEntity } from "@ceilgas/core/activity/models/index.js";
 *   import { ActivitySchemas } from "@ceilgas/core/activity/schemas/index.js";
 *
 *   // Flat schema imports
 *   import { ActivitySchemas, AiSchemas } from "@ceilgas/core";
 */

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate shared type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types (AccountId, OrgId, PageInfo, components, operations)
// NOTE: _shared is NOT a domain and is exported separately

import * as __shared from "./_shared/index.js";
import * as _bounds from "./bounds/index.js";
import * as _builds from "./builds/index.js";
import * as _certificates from "./certificates/index.js";
import * as _functions from "./functions/index.js";
import * as _griefing from "./griefing/index.js";
import * as _identity from "./identity/index.js";
import * as _monitors from "./monitors/index.js";
import * as _policies from "./policies/index.js";
import * as _recommendations from "./recommendations/index.js";

// Export as namespaces
export const _shared = __shared;
export const bounds = _bounds;
export const builds = _builds;
export const certificates = _certificates;
export const functions = _functions;
export const griefing = _griefing;
export const identity = _identity;
export const monitors = _monitors;
export const policies = _policies;
export const recommendations = _recommendations;

// ============================================================================
// FLAT EXPORTS (for direct imports)
// ============================================================================
// Export schemas from each domain for convenience
// NOTE: Types, repositories, models, and value-objects are available via:
//   - Namespace exports: import { activity } from "@ceilgas/core"; activity.types.*
//   - Direct exports: import * from "@ceilgas/core/activity/types/index.js"
//   - Direct exports: import * from "@ceilgas/core/activity/repositories/index.js"
//   - Direct exports: import * from "@ceilgas/core/activity/models/index.js"
//   - Direct exports: import * from "@ceilgas/core/activity/value-objects/index.js"

// Shared utilities and helpers
// These exports are required by platform/api-server and platform/services
export {
  DOMAIN_PREFIX_MAP,
  isValidDomainId,
  extractDomainFromId,
} from "./_shared/index.js";
export type { DomainCode, DomainPrefix } from "./_shared/index.js";

// Bounds Service
export { schemas as BoundsSchemas } from "./bounds/schemas/bounds.schemas.js";

// Builds Service
export { schemas as BuildsSchemas } from "./builds/schemas/builds.schemas.js";

// Certificates Service
export { schemas as CertificatesSchemas } from "./certificates/schemas/certificates.schemas.js";

// Functions Service
export { schemas as FunctionsSchemas } from "./functions/schemas/functions.schemas.js";

// Griefing Service
export { schemas as GriefingSchemas } from "./griefing/schemas/griefing.schemas.js";

// Identity Service
export { schemas as IdentitySchemas } from "./identity/schemas/identity.schemas.js";

// Monitors Service
export { schemas as MonitorsSchemas } from "./monitors/schemas/monitors.schemas.js";

// Policies Service
export { schemas as PoliciesSchemas } from "./policies/schemas/policies.schemas.js";

// Recommendations Service
export { schemas as RecommendationsSchemas } from "./recommendations/schemas/recommendations.schemas.js";

