/**
 * Griefing DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: griefing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Griefing Domain Module - Composition root
 *
 * DDD: Composition root for griefing domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  EstimateRepositoryAdapter,
} from "@ceilgas/adapters/griefing";
import { getIdGeneratorService } from "@ceilgas/adapters";
import type { AdapterDynamoDBClient } from "@ceilgas/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateGriefingEstimate,
  ExecuteListGriefingEstimates,
} from "@ceilgas/services/griefing/usecases";
// Ports (interfaces)
import type {
  EstimateRepository,
} from "@ceilgas/services/griefing/ports";

export interface GriefingDomainModule {
  repos: {
    estimates: EstimateRepository;
  };
  useCases: {
    estimates: {
      create: ExecuteCreateGriefingEstimate;
      list: ExecuteListGriefingEstimates;
    };
  };
}

export function buildGriefingDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): GriefingDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      estimates?: EstimateRepository;
    } = {};

    obj.estimates = new EstimateRepositoryAdapter(dynamoClient);
    return {
      estimates: obj.estimates!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    estimates: {
      create: new ExecuteCreateGriefingEstimate(executionContext, idGenerator, repos.estimates),
      list: new ExecuteListGriefingEstimates(executionContext, idGenerator, repos.estimates),
    },
  };
  return { repos, useCases: useCases as GriefingDomainModule["useCases"] };
}
