/**
 * FunctionRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: functions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * FunctionRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements FunctionRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  FunctionRepository,
} from "@ceilgas/services/functions";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { FunctionRepositoryDdb } from "./function-repository.ddb.js";

/**
 * FunctionRepositoryAdapter
 *
 * Implements FunctionRepository port for infrastructure layer.
 */
export class FunctionRepositoryAdapter implements FunctionRepository {
  private readonly ddb: FunctionRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new FunctionRepositoryDdb(this.dynamoClient);
  }

  async listFunctions(input: Parameters<FunctionRepository['listFunctions']>[0]): Promise<Awaited<ReturnType<FunctionRepository['listFunctions']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listFunctions(input);
  }

  async getFunction(input: Parameters<FunctionRepository['getFunction']>[0]): Promise<Awaited<ReturnType<FunctionRepository['getFunction']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getFunction(input);
  }
}
