/**
 * Certificate DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: certificates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Certificate DTOs
 *
 * DDD: Application DTOs for Certificate use cases.
 */

import type { GetGasCertificateParams, IssueGasCertificateRequestInput, ListGasCertificatesParams } from "@ceilgas/core/certificates/types";

export type ListGasCertificatesInput = ListGasCertificatesParams;

export type IssueGasCertificateInput = IssueGasCertificateRequestInput;

export type GetGasCertificateInput = GetGasCertificateParams;

export type ListGasCertificatesOutput = {};

export type IssueGasCertificateOutput = {};

export type GetGasCertificateOutput = {};
