/**
 * PolicyRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PolicyRepository Port
 *
 * DDD: Application port for policyrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetCiPolicyInput, GetCiPolicyOutput, ListCiPoliciesInput, ListCiPoliciesOutput, UpsertCiPolicyInput, UpsertCiPolicyOutput } from "../dto/policy.dto";
export interface PolicyRepository {
  listCiPolicies(input: ListCiPoliciesInput): Promise<ListCiPoliciesOutput>;
  upsertCiPolicy(input: UpsertCiPolicyInput): Promise<UpsertCiPolicyOutput>;
  getCiPolicy(input: GetCiPolicyInput): Promise<GetCiPolicyOutput>;
}

export type { GetCiPolicyInput, GetCiPolicyOutput, ListCiPoliciesInput, ListCiPoliciesOutput, UpsertCiPolicyInput, UpsertCiPolicyOutput } from "../dto/policy.dto";
