/**
 * GetPolicy DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetCiPolicyParams } from "@ceilgas/core/policies";

export function createGetPolicyRequest(overrides: Partial<GetCiPolicyParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
