/**
 * In-memory Ceilgas product domain store (sandbox).
 * Hand-maintained — not regenerated by codegen.
 */

import { createHash } from "node:crypto";
import { ulid } from "ulid";

export function nowIso(): string {
  return new Date().toISOString();
}

export function meta(correlationId?: string) {
  return {
    meta: {
      correlationId: correlationId ?? `cor_${ulid().toLowerCase()}`,
      generatedAt: nowIso(),
      requestId: `req_${ulid().toLowerCase()}`,
      timestamp: nowIso(),
    },
  };
}

export function id(prefix: string): string {
  return `${prefix}_${ulid().toLowerCase()}`;
}

export function bytecodeHash(hex: string): string {
  return createHash("sha256").update(hex).digest("hex");
}

export type ContractBuild = {
  id: string;
  bytecodeHash: string;
  sourceLanguage?: string;
  status: "queued" | "analysing" | "completed" | "failed";
  cfgComplete?: boolean;
  analyserVersion?: string;
  gasScheduleVersion?: string;
  progressPercent?: number;
  failureReason?: string;
  createdAt: string;
  completedAt?: string;
};

export type PublicFunction = {
  id: string;
  buildId: string;
  name: string;
  selector?: string;
  isConstantGas?: boolean;
  sizeMetrics?: Array<{ name: string; kind: string; description?: string }>;
  analysisStatus?: string;
};

export type GasBound = {
  id: string;
  functionId: string;
  buildId?: string;
  status: "proven" | "incomplete";
  opcodeBoundFormula?: string;
  memoryBoundFormula?: string;
  incompletenessClass: string;
  residualRiskNote?: string;
  nonConstantPolicyFlag?: boolean;
  analysedAt?: string;
};

export type GasCertificate = {
  id: string;
  buildId: string;
  bytecodeHash: string;
  analyserVersion: string;
  gasScheduleVersion: string;
  status: "certified" | "partial" | "refused";
  assumptions?: Record<string, number>;
  refusedReason?: string;
  incompleteFunctionIds?: string[];
  issuedAt: string;
};

export type LimitRecommendation = {
  id: string;
  functionId: string;
  recommendedGasLimit: number;
  assumptions?: Record<string, number>;
  sound: boolean;
  callbackContext?: boolean;
  safetyMarginPercent?: number;
  createdAt?: string;
};

export type AssumptionMonitor = {
  id: string;
  certificateId: string;
  metricName: string;
  threshold: number;
  status: "active" | "paused" | "breached";
  lastObservedValue?: number;
  proximityRatio?: number;
  createdAt?: string;
};

export type MonitorAlert = {
  id: string;
  monitorId: string;
  observedValue: number;
  acknowledged?: boolean;
  createdAt: string;
};

export type CiPolicy = {
  id: string;
  name: string;
  mode: "certification" | "optimisation_hints";
  failClosedOnIncompleteness: boolean;
  nonConstantSeverity: "info" | "warn" | "fail";
  exceptionNotes?: string[];
  updatedAt?: string;
};

export type GriefingEstimate = {
  id: string;
  functionId: string;
  estimatedCostWei: string;
  assumptions?: Record<string, number>;
  labelledAdversarial: boolean;
  notes?: string;
  createdAt: string;
  createdByUserId?: string;
};

export const builds = new Map<string, ContractBuild>();
export const functions = new Map<string, PublicFunction>();
export const bounds = new Map<string, GasBound>();
export const certificates = new Map<string, GasCertificate>();
export const recommendations = new Map<string, LimitRecommendation>();
export const monitors = new Map<string, AssumptionMonitor>();
export const alerts = new Map<string, MonitorAlert>();
export const policies = new Map<string, CiPolicy>();
export const griefingEstimates = new Map<string, GriefingEstimate>();

/** Seed one demo pipeline so the console is non-empty on first load. */
export function ensureDemoSeed(): void {
  if (builds.size > 0) return;
  const buildId = "bld_01demo00000000000000000001";
  const fnId = "fnc_01demo00000000000000000001";
  const boundId = "bnd_01demo00000000000000000001";
  const certId = "crt_01demo00000000000000000001";
  const now = nowIso();
  builds.set(buildId, {
    id: buildId,
    bytecodeHash: "a".repeat(64),
    sourceLanguage: "solidity",
    status: "completed",
    cfgComplete: true,
    analyserVersion: "ceilgas-analyser@0.1.0",
    gasScheduleVersion: "london",
    progressPercent: 100,
    createdAt: now,
    completedAt: now,
  });
  functions.set(fnId, {
    id: fnId,
    buildId,
    name: "findWinner",
    selector: "0xabcdef01",
    isConstantGas: false,
    sizeMetrics: [
      { name: "slots.length", kind: "storage", description: "Lottery slots array length" },
      { name: "addresses.length", kind: "storage" },
    ],
    analysisStatus: "proven",
  });
  bounds.set(boundId, {
    id: boundId,
    functionId: fnId,
    buildId,
    status: "proven",
    opcodeBoundFormula: "21000 + 75 * slots.length",
    memoryBoundFormula: "3 * addresses.length",
    incompletenessClass: "none",
    nonConstantPolicyFlag: true,
    analysedAt: now,
  });
  certificates.set(certId, {
    id: certId,
    buildId,
    bytecodeHash: "a".repeat(64),
    analyserVersion: "ceilgas-analyser@0.1.0",
    gasScheduleVersion: "london",
    status: "certified",
    assumptions: { "slots.length": 25 },
    issuedAt: now,
  });
  const polId = "pol_01demo00000000000000000001";
  policies.set(polId, {
    id: polId,
    name: "default-ci",
    mode: "certification",
    failClosedOnIncompleteness: true,
    nonConstantSeverity: "fail",
    exceptionNotes: [],
    updatedAt: now,
  });
}
