/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: functions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Functions Domain Use Cases
 * 
 * List of all use case names for the functions domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const FUNCTIONS_USE_CASES = [
  "executeGetFunction",
  "executeListFunctions"
] as const;
