/**
 * BuildRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: builds
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * BuildRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements BuildRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  BuildRepository,
} from "@ceilgas/services/builds";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { BuildRepositoryDdb } from "./build-repository.ddb.js";

/**
 * BuildRepositoryAdapter
 *
 * Implements BuildRepository port for infrastructure layer.
 */
export class BuildRepositoryAdapter implements BuildRepository {
  private readonly ddb: BuildRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new BuildRepositoryDdb(this.dynamoClient);
  }

  async listBuilds(input: Parameters<BuildRepository['listBuilds']>[0]): Promise<Awaited<ReturnType<BuildRepository['listBuilds']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listBuilds(input);
  }

  async submitBuild(input: Parameters<BuildRepository['submitBuild']>[0]): Promise<Awaited<ReturnType<BuildRepository['submitBuild']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.submitBuild(input);
  }

  async getBuild(input: Parameters<BuildRepository['getBuild']>[0]): Promise<Awaited<ReturnType<BuildRepository['getBuild']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getBuild(input);
  }
}
