/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: griefing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Griefing Domain Use Cases
 * 
 * List of all use case names for the griefing domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const GRIEFING_USE_CASES = [
  "executeCreateGriefingEstimate",
  "executeListGriefingEstimates"
] as const;
