/**
 * Bound DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: bounds
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Bound DTOs
 *
 * DDD: Application DTOs for Bound use cases.
 */

import type { GetFunctionBoundsParams, ListBoundsParams } from "@ceilgas/core/bounds/types";

export type GetFunctionBoundsInput = GetFunctionBoundsParams;

export type ListBoundsInput = ListBoundsParams;

export type GetFunctionBoundsOutput = {};

export type ListBoundsOutput = {};
