/**
 * Functions DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: functions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Functions Domain Module - Composition root
 *
 * DDD: Composition root for functions domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  FunctionRepositoryAdapter,
} from "@ceilgas/adapters/functions";
import { getIdGeneratorService } from "@ceilgas/adapters";
import type { AdapterDynamoDBClient } from "@ceilgas/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteGetFunction,
  ExecuteListFunctions,
} from "@ceilgas/services/functions/usecases";
// Ports (interfaces)
import type {
  FunctionRepository,
} from "@ceilgas/services/functions/ports";

export interface FunctionsDomainModule {
  repos: {
    functions: FunctionRepository;
  };
  useCases: {
    functions: {
      get: ExecuteGetFunction;
      list: ExecuteListFunctions;
    };
  };
}

export function buildFunctionsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): FunctionsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      functions?: FunctionRepository;
    } = {};

    obj.functions = new FunctionRepositoryAdapter(dynamoClient);
    return {
      functions: obj.functions!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    functions: {
      get: new ExecuteGetFunction(executionContext, idGenerator, repos.functions),
      list: new ExecuteListFunctions(executionContext, idGenerator, repos.functions),
    },
  };
  return { repos, useCases: useCases as FunctionsDomainModule["useCases"] };
}
