/**
 * Domains Barrel Export
 *
 * AUTO-GENERATED by codegen (api_server_domain_routes). Do not edit by hand.
 * Centralized exports for all domain dependency builders and types.
 */

// Export all domain dependency builders
export { buildBoundsDomainModule } from "./bounds/dependencies/bounds-ddd.dependencies.js";
export { buildBuildsDomainModule } from "./builds/dependencies/builds-ddd.dependencies.js";
export { buildCertificatesDomainModule } from "./certificates/dependencies/certificates-ddd.dependencies.js";
export { buildFunctionsDomainModule } from "./functions/dependencies/functions-ddd.dependencies.js";
export { buildGriefingDomainModule } from "./griefing/dependencies/griefing-ddd.dependencies.js";
export { buildIdentityDomainModule } from "./identity/dependencies/identity-ddd.dependencies.js";
export { buildMonitorsDomainModule } from "./monitors/dependencies/monitors-ddd.dependencies.js";
export { buildPoliciesDomainModule } from "./policies/dependencies/policies-ddd.dependencies.js";
export { buildRecommendationsDomainModule } from "./recommendations/dependencies/recommendations-ddd.dependencies.js";

// Export all domain dependency types
export type { BoundsDomainModule } from "./bounds/dependencies/bounds-ddd.dependencies.js";
export type { BuildsDomainModule } from "./builds/dependencies/builds-ddd.dependencies.js";
export type { CertificatesDomainModule } from "./certificates/dependencies/certificates-ddd.dependencies.js";
export type { FunctionsDomainModule } from "./functions/dependencies/functions-ddd.dependencies.js";
export type { GriefingDomainModule } from "./griefing/dependencies/griefing-ddd.dependencies.js";
export type { IdentityDomainModule } from "./identity/dependencies/identity-ddd.dependencies.js";
export type { MonitorsDomainModule } from "./monitors/dependencies/monitors-ddd.dependencies.js";
export type { PoliciesDomainModule } from "./policies/dependencies/policies-ddd.dependencies.js";
export type { RecommendationsDomainModule } from "./recommendations/dependencies/recommendations-ddd.dependencies.js";
