/**
 * BoundRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: bounds
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * BoundRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements BoundRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  BoundRepository,
} from "@ceilgas/services/bounds";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { BoundRepositoryDdb } from "./bound-repository.ddb.js";

/**
 * BoundRepositoryAdapter
 *
 * Implements BoundRepository port for infrastructure layer.
 */
export class BoundRepositoryAdapter implements BoundRepository {
  private readonly ddb: BoundRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new BoundRepositoryDdb(this.dynamoClient);
  }

  async getFunctionBounds(input: Parameters<BoundRepository['getFunctionBounds']>[0]): Promise<Awaited<ReturnType<BoundRepository['getFunctionBounds']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getFunctionBounds(input);
  }

  async listBounds(input: Parameters<BoundRepository['listBounds']>[0]): Promise<Awaited<ReturnType<BoundRepository['listBounds']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listBounds(input);
  }
}
