/**
 * ExecuteUpsertCiPolicy - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteUpsertCiPolicy Use Case
 *
 * DDD: Application use case for get Policy.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { UpsertCiPolicyInput, UpsertCiPolicyOutput } from "../dto/policy.dto";
import type { ExecutionContextService, IdGeneratorService } from "@ceilgas/services/_shared/index.js";
import type { PolicyRepository } from "../ports";
import { NotFoundError } from "../errors";

export class ExecuteUpsertCiPolicy {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly policy: PolicyRepository
  ) {}

  async execute(input: UpsertCiPolicyInput): Promise<UpsertCiPolicyOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.polId();

    // All field names extracted from OpenAPI spec: exceptionNotes, failClosedOnIncompleteness, mode, name, nonConstantSeverity
    // Load entity via repository (no ID field - uses input directly, pass correlation ID for response meta)
    const entity = await this.policy.upsertCiPolicy({ ...input, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found`);
    }

    return entity as UpsertCiPolicyOutput;
  }
}
