/**
 * Main Services Package Index
 *
 * Generated by Services Main Index Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: griefing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Services Package - Main Barrel Export
 *
 * Central export point for all application services (use cases, ports, DTOs, policies, errors)
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended)
 *   import { activity, ai, conversation } from "@ceilgas/services";
 *   const { usecases, dto, ports } = activity;
 *
 *   // Direct imports from domain
 *   import { ExecuteCreateEventUseCase } from "@ceilgas/services/activity";
 *   
 *   // Shared services
 *   import { executionContextService } from "@ceilgas/services";
 */

// ============================================================================
// SHARED SERVICES EXPORTS
// ============================================================================
export { executionContextService } from "./_shared/index.js";

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types across domains

import * as _bounds from "./bounds/index.js";
import * as _builds from "./builds/index.js";
import * as _certificates from "./certificates/index.js";
import * as _functions from "./functions/index.js";
import * as _griefing from "./griefing/index.js";
import * as _identity from "./identity/index.js";
import * as _monitors from "./monitors/index.js";
import * as _policies from "./policies/index.js";
import * as _recommendations from "./recommendations/index.js";

// Export as namespaces
export const bounds = _bounds;
export const builds = _builds;
export const certificates = _certificates;
export const functions = _functions;
export const griefing = _griefing;
export const identity = _identity;
export const monitors = _monitors;
export const policies = _policies;
export const recommendations = _recommendations;
