/**
 * Estimate DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: griefing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Estimate DTOs
 *
 * DDD: Application DTOs for Estimate use cases.
 */

import type { CreateGriefingEstimateRequestInput, ListGriefingEstimatesParams } from "@ceilgas/core/griefing/types";

export type ListGriefingEstimatesInput = ListGriefingEstimatesParams;

export type CreateGriefingEstimateInput = CreateGriefingEstimateRequestInput;

export type ListGriefingEstimatesOutput = {};

export type CreateGriefingEstimateOutput = {};
