/**
 * Monitors DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monitors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Monitors Domain Module - Composition root
 *
 * DDD: Composition root for monitors domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  AlertRepositoryAdapter,
  MonitorRepositoryAdapter,
} from "@ceilgas/adapters/monitors";
import { getIdGeneratorService } from "@ceilgas/adapters";
import type { AdapterDynamoDBClient } from "@ceilgas/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateMonitor,
  ExecuteListMonitorAlerts,
  ExecuteListMonitors,
} from "@ceilgas/services/monitors/usecases";
// Ports (interfaces)
import type {
  AlertRepository,
  MonitorRepository,
} from "@ceilgas/services/monitors/ports";

export interface MonitorsDomainModule {
  repos: {
    alerts: AlertRepository;
    monitors: MonitorRepository;
  };
  useCases: {
    alerts: {
      list: ExecuteListMonitorAlerts;
    };
    monitors: {
      create: ExecuteCreateMonitor;
      list: ExecuteListMonitors;
    };
  };
}

export function buildMonitorsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): MonitorsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      alerts?: AlertRepository;
      monitors?: MonitorRepository;
    } = {};

    obj.alerts = new AlertRepositoryAdapter(dynamoClient);
    obj.monitors = new MonitorRepositoryAdapter(dynamoClient);
    return {
      alerts: obj.alerts!,
      monitors: obj.monitors!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    alerts: {
      list: new ExecuteListMonitorAlerts(executionContext, idGenerator, repos.alerts),
    },
    monitors: {
      create: new ExecuteCreateMonitor(executionContext, idGenerator, repos.monitors),
      list: new ExecuteListMonitors(executionContext, idGenerator, repos.monitors),
    },
  };
  return { repos, useCases: useCases as MonitorsDomainModule["useCases"] };
}
