/**
 * ExecuteGetFunctionBounds - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: bounds
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetFunctionBounds Use Case
 *
 * DDD: Application use case for get Bound.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetFunctionBoundsInput, GetFunctionBoundsOutput } from "../dto/bound.dto";
import type { ExecutionContextService, IdGeneratorService } from "@ceilgas/services/_shared/index.js";
import type { BoundRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetFunctionBounds {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly bound: BoundRepository
  ) {}

  async execute(input: GetFunctionBoundsInput): Promise<GetFunctionBoundsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.bndId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).functionId) {
      throw new ValidationError("functionId is required");
    }
    const functionId = (input as any).functionId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.bound.getFunctionBounds({ functionId: functionId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${functionId}`);
    }

    return entity as GetFunctionBoundsOutput;
  }
}
