/**
 * ExecuteListBounds - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: bounds
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListBounds Use Case
 *
 * DDD: Application use case for list Bound.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListBoundsInput, ListBoundsOutput } from "../dto/bound.dto";
import type { ExecutionContextService, IdGeneratorService } from "@ceilgas/services/_shared/index.js";
import type { BoundRepository } from "../ports";

export class ExecuteListBounds {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly bound: BoundRepository
  ) {}

  async execute(input: ListBoundsInput): Promise<ListBoundsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.bndId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.bound.listBounds({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListBoundsOutput;
  }
}
