/**
 * Handlers for Policy
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { PoliciesDomainModule } from "../dependencies/policies-ddd.dependencies.js";
import type { GetCiPolicyInput, ListCiPoliciesInput, UpsertCiPolicyInput } from "@ceilgas/services/policies";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/policies
 * Operation: listCiPolicies
 */
export async function listCiPolicies(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: PoliciesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListCiPoliciesInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.policies.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/policies
 * Operation: upsertCiPolicy
 */
export async function upsertCiPolicy(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: PoliciesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: UpsertCiPolicyInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.policies.get.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for GET /v1/policies/{policyId}
 * Operation: getCiPolicy
 */
export async function getCiPolicy(
  request: FastifyRequest<{ Params: { policyId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: PoliciesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetCiPolicyInput = {
    policyId: request.params.policyId,
  };
  const result = await deps.useCases.policies.get.execute(input);
  return reply.code(200).send(result);
}


