/**
 * Bounds DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: bounds
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Bounds Domain Module - Composition root
 *
 * DDD: Composition root for bounds domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  BoundRepositoryAdapter,
} from "@ceilgas/adapters/bounds";
import { getIdGeneratorService } from "@ceilgas/adapters";
import type { AdapterDynamoDBClient } from "@ceilgas/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteGetFunctionBounds,
  ExecuteListBounds,
} from "@ceilgas/services/bounds/usecases";
// Ports (interfaces)
import type {
  BoundRepository,
} from "@ceilgas/services/bounds/ports";

export interface BoundsDomainModule {
  repos: {
    bounds: BoundRepository;
  };
  useCases: {
    bounds: {
      get: ExecuteGetFunctionBounds;
      list: ExecuteListBounds;
    };
  };
}

export function buildBoundsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): BoundsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      bounds?: BoundRepository;
    } = {};

    obj.bounds = new BoundRepositoryAdapter(dynamoClient);
    return {
      bounds: obj.bounds!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    bounds: {
      get: new ExecuteGetFunctionBounds(executionContext, idGenerator, repos.bounds),
      list: new ExecuteListBounds(executionContext, idGenerator, repos.bounds),
    },
  };
  return { repos, useCases: useCases as BoundsDomainModule["useCases"] };
}
