/**
 * GetFunctionBounds handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: bounds
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getFunctionBounds } from "@ceilgas/api-server/domains/bounds/handlers";
import type { BoundsDDDDependencies } from "@ceilgas/api-server/domains/bounds";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@ceilgas/tests/shared";
import { BOUNDS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetFunctionBounds", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: BoundsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<BoundsDDDDependencies>(
      BOUNDS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetFunctionBounds, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { functionId: entity.id };

    await getFunctionBounds(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetFunctionBounds.execute).toHaveBeenCalledWith(expect.objectContaining({ functionId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { functionId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetFunctionBounds, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getFunctionBounds(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
