/**
 * EstimateRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: griefing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * EstimateRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements EstimateRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  EstimateRepository,
} from "@ceilgas/services/griefing";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { EstimateRepositoryDdb } from "./estimate-repository.ddb.js";

/**
 * EstimateRepositoryAdapter
 *
 * Implements EstimateRepository port for infrastructure layer.
 */
export class EstimateRepositoryAdapter implements EstimateRepository {
  private readonly ddb: EstimateRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new EstimateRepositoryDdb(this.dynamoClient);
  }

  async listGriefingEstimates(input: Parameters<EstimateRepository['listGriefingEstimates']>[0]): Promise<Awaited<ReturnType<EstimateRepository['listGriefingEstimates']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listGriefingEstimates(input);
  }

  async createGriefingEstimate(input: Parameters<EstimateRepository['createGriefingEstimate']>[0]): Promise<Awaited<ReturnType<EstimateRepository['createGriefingEstimate']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createGriefingEstimate(input);
  }
}
