/**
 * ExecuteListLimitRecommendations - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: recommendations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListLimitRecommendations Use Case
 *
 * DDD: Application use case for list Recommendation.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListLimitRecommendationsInput, ListLimitRecommendationsOutput } from "../dto/recommendation.dto";
import type { ExecutionContextService, IdGeneratorService } from "@ceilgas/services/_shared/index.js";
import type { RecommendationRepository } from "../ports";

export class ExecuteListLimitRecommendations {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly recommendation: RecommendationRepository
  ) {}

  async execute(input: ListLimitRecommendationsInput): Promise<ListLimitRecommendationsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.recId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.recommendation.listLimitRecommendations({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListLimitRecommendationsOutput;
  }
}
