/**
 * Recommendations DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: recommendations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Recommendations Domain Module - Composition root
 *
 * DDD: Composition root for recommendations domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  RecommendationRepositoryAdapter,
} from "@ceilgas/adapters/recommendations";
import { getIdGeneratorService } from "@ceilgas/adapters";
import type { AdapterDynamoDBClient } from "@ceilgas/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateLimitRecommendation,
  ExecuteListLimitRecommendations,
} from "@ceilgas/services/recommendations/usecases";
// Ports (interfaces)
import type {
  RecommendationRepository,
} from "@ceilgas/services/recommendations/ports";

export interface RecommendationsDomainModule {
  repos: {
    recommendations: RecommendationRepository;
  };
  useCases: {
    recommendations: {
      create: ExecuteCreateLimitRecommendation;
      list: ExecuteListLimitRecommendations;
    };
  };
}

export function buildRecommendationsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): RecommendationsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      recommendations?: RecommendationRepository;
    } = {};

    obj.recommendations = new RecommendationRepositoryAdapter(dynamoClient);
    return {
      recommendations: obj.recommendations!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    recommendations: {
      create: new ExecuteCreateLimitRecommendation(executionContext, idGenerator, repos.recommendations),
      list: new ExecuteListLimitRecommendations(executionContext, idGenerator, repos.recommendations),
    },
  };
  return { repos, useCases: useCases as RecommendationsDomainModule["useCases"] };
}
