/**
 * Function DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: functions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Function DTOs
 *
 * DDD: Application DTOs for Function use cases.
 */

import type { GetFunctionParams, ListFunctionsParams } from "@ceilgas/core/functions/types";

export type ListFunctionsInput = ListFunctionsParams;

export type GetFunctionInput = GetFunctionParams;

export type ListFunctionsOutput = {};

export type GetFunctionOutput = {};
