/**
 * CertificateRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: certificates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CertificateRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements CertificateRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  CertificateRepository,
} from "@ceilgas/services/certificates";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { CertificateRepositoryDdb } from "./certificate-repository.ddb.js";

/**
 * CertificateRepositoryAdapter
 *
 * Implements CertificateRepository port for infrastructure layer.
 */
export class CertificateRepositoryAdapter implements CertificateRepository {
  private readonly ddb: CertificateRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new CertificateRepositoryDdb(this.dynamoClient);
  }

  async listGasCertificates(input: Parameters<CertificateRepository['listGasCertificates']>[0]): Promise<Awaited<ReturnType<CertificateRepository['listGasCertificates']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listGasCertificates(input);
  }

  async issueGasCertificate(input: Parameters<CertificateRepository['issueGasCertificate']>[0]): Promise<Awaited<ReturnType<CertificateRepository['issueGasCertificate']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.issueGasCertificate(input);
  }

  async getGasCertificate(input: Parameters<CertificateRepository['getGasCertificate']>[0]): Promise<Awaited<ReturnType<CertificateRepository['getGasCertificate']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getGasCertificate(input);
  }
}
