/**
 * Routes for Bound
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: bounds
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getFunctionBounds, listBounds } from "../handlers/bound.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function boundRoutes(fastify: FastifyInstance) {
  // GET /v1/bounds (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/bounds",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getBoundsDependenciesForRequest();
        await listBounds(request, reply, deps);
      });
    }
  );


  // GET /v1/functions/{functionId}/bounds (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/functions/:functionId/bounds",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { functionId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getBoundsDependenciesForRequest();
        await getFunctionBounds(request, reply, deps);
      });
    }
  );


}
