/**
 * BuildRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: builds
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * BuildRepository Port
 *
 * DDD: Application port for buildrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetBuildInput, GetBuildOutput, ListBuildsInput, ListBuildsOutput, SubmitBuildInput, SubmitBuildOutput } from "../dto/build.dto";
export interface BuildRepository {
  listBuilds(input: ListBuildsInput): Promise<ListBuildsOutput>;
  submitBuild(input: SubmitBuildInput): Promise<SubmitBuildOutput>;
  getBuild(input: GetBuildInput): Promise<GetBuildOutput>;
}

export type { GetBuildInput, GetBuildOutput, ListBuildsInput, ListBuildsOutput, SubmitBuildInput, SubmitBuildOutput } from "../dto/build.dto";
