/**
 * ExecuteListGasCertificates - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: certificates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListGasCertificates Use Case
 *
 * DDD: Application use case for list Certificate.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListGasCertificatesInput, ListGasCertificatesOutput } from "../dto/certificate.dto";
import type { ExecutionContextService, IdGeneratorService } from "@ceilgas/services/_shared/index.js";
import type { CertificateRepository } from "../ports";

export class ExecuteListGasCertificates {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly certificate: CertificateRepository
  ) {}

  async execute(input: ListGasCertificatesInput): Promise<ListGasCertificatesOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.crtId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.certificate.listGasCertificates({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListGasCertificatesOutput;
  }
}
